apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-html-configmap
  namespace: gifs-website
data:
  index.html: |
    <html>
    <head>
        <title>Daniel Gifs Website</title>
        <style>
            body {
                background-color: #f2f2f2;
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
            }

            section {
                background-color: #fff;
                padding: 20px;
                margin-bottom: 20px;
            }

            button {
                background-color: #4CAF50;
                border: none;
                color: white;
                padding: 10px 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
            }

            header {
                background-color: #333;
                padding: 20px;
                color: #fff;
            }

            nav ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                overflow: hidden;
            }

            nav ul li {
                display: inline;
            }

            nav ul li a {
                color: #fff;
                padding: 10px;
                text-decoration: none;
            }

            nav ul li a:hover {
                background-color: #555;
            }

            header h1 {
                margin: 0;
            }

            p {
                margin: 10px 0;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Welcome to Daniel Gifs Website</h1>
            <nav>
                <ul>
                    <li><a href="#dogs">Dogs Gifs</a></li>
                    <li><a href="#alpacas">Classmates Gifs</a></li>
                    <li><a href="#classmates">Alpacas Gifs</a></li>
                </ul>
            </nav>
        </header>

        <section id="dogs">
            <h2>Dogs Gifs</h2>
            <p>Click the button below to explore Dogs Gifs:</p>
            <button onclick="window.location.href='http://34.122.5.102:80'">Explore Dogs Gifs</button>
        </section>

        <section id="classmates">
            <h2>Classmates Gifs</h2>
            <p>Click the button below to explore Classmates Gifs:</p>
            <button onclick="window.location.href='http://34.173.230.3:80'">Explore Classmates Gifs</button>
        </section>

        <section id="alpacas">
            <h2>Alpacas Gifs</h2>
            <p>Click the button below to explore Alpacas Gifs:</p>
            <button onclick="window.location.href='http://34.170.180.92:80'">Explore Alpacas Gifs</button>
        </section>

        <footer>
            <p>&copy; 2023 Daniel Gifs Website. All rights reserved.</p>
        </footer>
    </body>
    </html>